name: release merge success notification through MS Teams

# 工作流程會在 PR 被合併到 develop 分支後觸發
on:
    pull_request:
        types:
            - closed # 只在 PR 被關閉（合併）的情況下觸發
        branches:
            - develop # 僅當 PR 是合併到 develop 分支時觸發

jobs:
    merge:
        # 只有當 PR 已被合併時（而不是單純關閉）才會執行
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        steps:
            - name: send notification to MS Teams
              env:
                  TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL }} # 在 GitHub Secrets 中添加你的 Webhook URL
              run: |
                  curl -H 'Content-Type: application/json' -d '{
                      "text": "專案:${{github.repository}}分支:${{github.ref_name}}已上線，感謝該專案開發人員，並請確認下次上線功能是否有環境可以佈版測試。"
                  }' $TEAMS_WEBHOOK_URL
