name: release merge success notification through MS Teams

# 工作流程會在 PR 被合併到 develop 分支後觸發
on:
    pull_request:
        types:
            - closed # 只在 PR 被關閉（合併）的情況下觸發
        branches:
            - develop # 僅當 PR 是合併到 develop 分支時觸發

jobs:
    merge:
        name: Microsoft Teams Notification
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true
        steps:
            - name: Send Notification to Power Automate
              run: |
                  curl -X POST -H "Content-Type: application/json" -d '{
                  "type": "message",
                  "title": "原生寫法測試",
                      "attachments": [
                      {
                          "contentType": "application/vnd.microsoft.card.adaptive",
                          "content": {
                          "type": "AdaptiveCard",
                          "body": [
                              {
                              "type": "TextBlock",
                              "text": "專案: ${{ github.repository }} 分支: ${{ github.ref_name }} 已上線，感謝該專案開發人員，並請確認下次上線功能是否有環境可以佈版測試。"
                              }
                          ]
                          }
                      }
                      ]
                  }' ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL }}
