name: release merge success notification

on:
    push:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Send mail
              uses: dawidd6/action-send-mail@v3
              with:
                  # Specify connection via URL (replaces server_address, server_port, secure,
                  # username and password)
                  #
                  # Format:
                  #
                  #  * smtp://user:password@server:port
                  #  * smtp+starttls://user:password@server:port
                  connection_url: smtp+starttls://jayhan0905@gmail.com:lgzunepluqstkpul@smtp.gmail.com:465
                  # Required mail server address if not connection_url:
                  server_address: smtp.gmail.com
                  # Server port, default 25:
                  server_port: 465
                  # Optional whether this connection use TLS (default is true if server_port is 465)
                  secure: true
                  # Optional (recommended) mail server username:
                  username: jayhan0905@gmail.com
                  # Optional (recommended) mail server password:
                  password: lgzunepluqstkpul
                  # Required mail subject:
                  subject: Github Actions job result
                  # Required recipients' addresses:
                  to: ed.lin@devpro.com.tw
                  # Required sender full name (address can be skipped):
                  from: Ed.Lin # <user@example.com>
                  # Optional plain body:
                  body: Build job of ${{github.repository}} completed successfully!
                  # Optional carbon copy recipients:
                  cc: ed.lin@devpro.com.tw
                  # Optional blind carbon copy recipients:
                  bcc: ed.lin@devpro.com.tw
