name: release merge success notification

# 工作流程會在 PR 被合併到 develop 分支後觸發
on:
    pull_request:
        types:
            - closed # 只在 PR 被關閉（合併）的情況下觸發
        branches:
            - develop # 僅當 PR 是合併到 develop 分支時觸發

env:
    EMAIL_RECIPIENTS: 'ed.lin@devpro.com.tw,user@example.com'

jobs:
    merge:
        # 只有當 PR 已被合併時（而不是單純關閉）才會執行
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        steps:
            - name: Send mail
              uses: dawidd6/action-send-mail@v3
              with:
                  # Specify connection via URL (replaces server_address, server_port, secure,
                  # username and password)
                  #
                  # Format:
                  #
                  #  * smtp://user:password@server:port
                  #  * smtp+starttls://user:password@server:port
                  connection_url: ${{secrets.MAIL_CONNECTION}}
                  # Required mail server address if not connection_url:
                  server_address: smtp.gmail.com
                  # Server port, default 25:
                  server_port: 465
                  # Optional whether this connection use TLS (default is true if server_port is 465)
                  secure: true
                  # Optional (recommended) mail server username:
                  username: ${{secrets.MAIL_USERNAME}}
                  # Optional (recommended) mail server password:
                  password: ${{secrets.MAIL_PASSWORD}}
                  # Required mail subject:
                  subject: release分支PR合併成功通知
                  # Required recipients' addresses:
                  to: ${{ env.EMAIL_RECIPIENTS }}
                  # Required sender full name (address can be skipped):
                  from: notifications@github.com # <user@example.com>
                  # Optional plain body:
                  body: 專案 ${{github.repository}} ${{github.ref_name}}已上線，感謝該專案開發人員，並請確認下次上線功能是否有環境可以佈版測試。
