name: release merge success notification through MS Teams

# 工作流程會在 PR 被合併到 develop 分支後觸發
on:
    pull_request:
        types:
            - closed # 只在 PR 被關閉（合併）的情況下觸發
        branches:
            - develop # 僅當 PR 是合併到 develop 分支時觸發

jobs:
    merge:
        name: Microsoft Teams Notification
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Send Notification to Power Automate
              run: |
                  curl -H "Content-Type: application/json" \
                  -d '{
                    "@type": "MessageCard",
                    "@context": "http://schema.org/extensions",
                    "themeColor": "0076D7",
                    "summary": "PR 合併通知",
                    "sections": [{
                      "activityTitle": "PR 合併通知",
                      "activitySubtitle": "專案資訊",
                      "facts": [
                        {
                          "name": "專案名稱",
                          "value": "${{ github.repository }}"
                        },
                        {
                          "name": "分支",
                          "value": "${{ github.ref_name }}"
                        }
                      ],
                      "text": "已上線，感謝該專案開發人員，並請確認下次上線功能是否有環境可以佈版測試。"
                    }]
                  }' ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL }}
